### ISSUE TITLE
Import unicode_literals

### ISSUE THREAD

**Issue by weaverba137** [sdss/python_template#1]
The coding standards recommend
```python
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import
```
but oddly, not
```python
from __future__ import unicode_literals
```
That one is actually the most important for catching 2 to 3 transition problems.

**Comment by albireox** [comment]
I'd like to have more discussion on this. Doing a quick search it seems that there are pros and cons to using `unicode_literals`: http://python-future.org/unicode_literals.html

What are people opinions on this? @andycasey @havok2063

**Comment by weaverba137** [comment]
Here is the specific reference to the Astropy documentation that implies that `unicode_literals` is required by `six`: http://docs.astropy.org/en/stable/development/codeguide.html#interface-and-dependencies

**Comment by albireox** [comment]
I've added to the coding standards and to the files in the template.
