### ISSUE TITLE
Misplaced quotation marks in python_template.module module-whatis statement.

### ISSUE THREAD

**Issue by nbmurphy** [sdss/python_template#10]
In the file `python_template/{{cookiecutter.repo_name}}/etc/{{cookiecutter.package_name}}.module` 
shouldn’t the line
`module-whatis {{"Sets up $product/$version in your environment."}}`
instead be
`module-whatis "{{Sets up $product/$version in your environment.}}"`
so the quotation marks don’t get replaced in the sdss_install substitution?

**Comment by albireox** [comment]
Sorry for the delay with this. It's fixed now and released in 1.0.3.

**Comment by nbmurphy** [comment]
The previous suggested change does not seem to be the correct solution to the previous problem. I just tried to create a cookiecutted python template and it threw the following error:

`File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'up'
  File "./etc/{{cookiecutter.package_name}}.module", line 37
    module-whatis "{{Sets up $product/$version in your environment.}}" `

**Comment by nbmurphy** [comment]
@albireox removed the braces in `module-whatis "{{Sets up $product/$version in your environment.}}"` so it now reads `module-whatis "Sets up $product/$version in your environment."` I tested the change and it seems to work.
