### ISSUE TITLE
bumpversion installation

### ISSUE THREAD

**Issue by andycasey** [sdss/python_template#2]
Should `bumpversion` be installed at the start of the documentation at http://sdss-python-template.readthedocs.io/en/latest/ in the same way  that `invoke` is installed? Later in the documentation `bumpversion` is referred to (in a similar way that `invoke` is), but `bumpversion` may not be installed.

**Comment by albireox** [comment]
I think this is probably a good idea. Arguably the template only needs cookiecutter to be installed (and people may not want to use bumpversion or invoke). In that case maybe the `pip install invoke` should be moved to the section in which we explain how to use invoke.

Thought? In principle I lean towards doing what Andy suggests.

**Comment by havok2063** [comment]
If we're planning on keeping the template lean, then I lean towards including the bumpversion in the install instructions.  If we start adding more functionality, then this will get large, in which case I'd rather move each `pip install` into their respective sections. 

Other cookiecutter templates provide a bunch of functionality but don't explicitly include the `pip installs` in their installation instructions.  There merely mention you get this functionality and link to individual package pages.

**Comment by albireox** [comment]
Sounds good. I have added it to the install instructions.
