### ISSUE TITLE
Move change log into sphinx directory?

### ISSUE THREAD

**Issue by weaverba137** [sdss/python_template#4]
The change log file is at the top-level of the output directory.  However, if it were moved inside the docs/sphinx directory, it would be visible in the Sphinx/ReadTheDocs documentation, which is often useful.

**Comment by albireox** [comment]
Right now what we do it do link it in https://raw.githubusercontent.com/sdss/python_template/master/%7B%7Bcookiecutter.repo_name%7D%7D/docs/sphinx/CHANGELOG.rst, which simply includes an include to the CHANGELOG two levels up. I think that keeps the CHANGELOG in a pretty visible place while still making it available to the Sphinx docs.

**Comment by weaverba137** [comment]
If it is already being included in the Sphinx output, then there's no need to move it.
